version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:ci
  post_build:
    commands:
      - aws s3 sync ./dist/serverless s3://virginiaboyinc.com --acl 'public-read' --delete